import { Book } from "./books.en";

export const BOOKS_DE: Book[] = [
  { name: "1. Mose", aliases: ["Genesis", "Gen", "1Mo"] },
  { name: "2. Mose", aliases: ["Exodus", "Ex", "2Mo"] },
  { name: "3. Mose", aliases: ["Levitikus", "Lev", "3Mo"] },
  { name: "4. Mose", aliases: ["Numeri", "Num", "4Mo"] },
  { name: "5. Mose", aliases: ["Deuteronomium", "Dtn", "5Mo"] },
  { name: "Josua", aliases: ["Jos", "Jos"] },
  { name: "Richter", aliases: ["Ri", "Richt"] },
  { name: "Rut", aliases: ["Rut", "Ru"] },
  { name: "1. Samuel", aliases: ["1Sam", "1Sa"] },
  { name: "2. Samuel", aliases: ["2Sam", "2Sa"] },
  { name: "1. Könige", aliases: ["1Kön", "1Kö"] },
  { name: "2. Könige", aliases: ["2Kön", "2Kö"] },
  { name: "1. Chronik", aliases: ["1Chr", "1Ch"] },
  { name: "2. Chronik", aliases: ["2Chr", "2Ch"] },
  { name: "Esra", aliases: ["Esr", "Esr"] },
  { name: "Nehemia", aliases: ["Neh", "Neh"] },
  { name: "Ester", aliases: ["Esther", "Est", "Est"] },
  { name: "Ijob", aliases: ["Hiob", "Ijob", "Hi"] },
  { name: "Psalmen", aliases: ["Psalter", "Ps"] },
  { name: "Sprüche", aliases: ["Sprüche Salomos", "Spr"] },
  { name: "Kohelet", aliases: ["Prediger", "Koh", "Pred"] },
  { name: "Hoheslied", aliases: ["Lied der Lieder", "Hld", "Hl"] },
  { name: "Jesaja", aliases: ["Jes"] },
  { name: "Jeremia", aliases: ["Jer"] },
  { name: "Klagelieder", aliases: ["Threni", "Klgl", "Kla"] },
  { name: "Ezechiel", aliases: ["Hesekiel", "Ez", "Hes"] },
  { name: "Daniel", aliases: ["Dan"] },
  { name: "Hosea", aliases: ["Hos", "Hos"] },
  { name: "Joel", aliases: ["Joe"] },
  { name: "Amos", aliases: ["Am", "Amos"] },
  { name: "Obadja", aliases: ["Ob", "Oba"] },
  { name: "Jona", aliases: ["Jon"] },
  { name: "Micha", aliases: ["Mi", "Mic"] },
  { name: "Nahum", aliases: ["Nah"] },
  { name: "Habakuk", aliases: ["Hab", "Hab"] },
  { name: "Zefanja", aliases: ["Zephanja", "Zef", "Zeph"] },
  { name: "Haggai", aliases: ["Hag"] },
  { name: "Sacharja", aliases: ["Sach"] },
  { name: "Maleachi", aliases: ["Mal"] },
  { name: "Matthäus", aliases: ["Mt"] },
  { name: "Markus", aliases: ["Mk"] },
  { name: "Lukas", aliases: ["Lk"] },
  { name: "Johannes", aliases: ["Joh"] },
  { name: "Apostelgeschichte", aliases: ["Taten der Apostel", "Apg"] },
  { name: "Römer", aliases: ["Röm", "Rö"] },
  { name: "1. Korinther", aliases: ["1Kor", "1Ko"] },
  { name: "2. Korinther", aliases: ["2Kor", "2Ko"] },
  { name: "Galater", aliases: ["Gal", "Gal"] },
  { name: "Epheser", aliases: ["Eph", "Eph"] },
  { name: "Philipper", aliases: ["Phil"] },
  { name: "Kolosser", aliases: ["Kol"] },
  { name: "1. Thessalonicher", aliases: ["1Thes", "1Th"] },
  { name: "2. Thessalonicher", aliases: ["2Thes", "2Th"] },
  { name: "1. Timotheus", aliases: ["1Tim", "1Ti"] },
  { name: "2. Timotheus", aliases: ["2Tim", "2Ti"] },
  { name: "Titus", aliases: ["Tit"] },
  { name: "Philemon", aliases: ["Phlm", "Phm"] },
  { name: "Hebräer", aliases: ["Hebr", "Heb"] },
  { name: "Jakobus", aliases: ["Jak", "Jak"] },
  { name: "1. Petrus", aliases: ["1Pet", "1Pe"] },
  { name: "2. Petrus", aliases: ["2Pet", "2Pe"] },
  { name: "1. Johannes", aliases: ["1Joh", "1Jo"] },
  { name: "2. Johannes", aliases: ["2Joh", "2Jo"] },
  { name: "3. Johannes", aliases: ["3Joh", "3Jo"] },
  { name: "Judas", aliases: ["Jud"] },
  { name: "Offenbarung", aliases: ["Apokalypse", "Off", "Apk"] },
];