export interface Book {
    name: string;
    aliases: string[];
}

export const BOOKS: Book[] = [
    { name: "Genesis", aliases: ["gen"] },
    { name: "Exodus", aliases: ["exo"] },
    { name: "Leviticus", aliases: ["lev"] },
    { name: "Numbers", aliases: ["num"] },
    { name: "Deuteronomy", aliases: ["deu"] },
    { name: "Joshua", aliases: ["jos"] },
    { name: "Judges", aliases: ["jdg"] },
    { name: "Ruth", aliases: ["rut"] },
    { name: "1 Samuel", aliases: ["1sa", "1samuel"] },
    { name: "2 Samuel", aliases: ["2sa", "2samuel"] },
    { name: "1 Kings", aliases: ["1ki", "1kings"] },
    { name: "2 Kings", aliases: ["2ki", "2kings"] },
    { name: "1 Chronicles", aliases: ["1ch", "1chronicles"] },
    { name: "2 Chronicles", aliases: ["2ch", "2chronicles"] },
    { name: "Ezra", aliases: ["ezr"] },
    { name: "Nehemiah", aliases: ["neh"] },
    { name: "Esther", aliases: ["est"] },
    { name: "Job", aliases: ["job"] },
    { name: "Psalms", aliases: ["psa"] },
    { name: "Proverbs", aliases: ["pro"] },
    { name: "Ecclesiastes", aliases: ["ecc"] },
    { name: "Song of Songs", aliases: ["sng", "Song of Solomon"] },
    { name: "Isaiah", aliases: ["isa"] },
    { name: "Jeremiah", aliases: ["jer"] },
    { name: "Lamentations", aliases: ["lam"] },
    { name: "Ezekiel", aliases: ["ezk"] },
    { name: "Daniel", aliases: ["dan"] },
    { name: "Hosea", aliases: ["hos"] },
    { name: "Joel", aliases: ["jol"] },
    { name: "Amos", aliases: ["amo"] },
    { name: "Obadiah", aliases: ["oba"] },
    { name: "Jonah", aliases: ["jon"] },
    { name: "Micah", aliases: ["mic"] },
    { name: "Nahum", aliases: ["nam"] },
    { name: "Habakkuk", aliases: ["hab"] },
    { name: "Zephaniah", aliases: ["zep"] },
    { name: "Haggai", aliases: ["hag"] },
    { name: "Zechariah", aliases: ["zec"] },
    { name: "Malachi", aliases: ["mal"] },
    { name: "Matthew", aliases: ["mat"] },
    { name: "Mark", aliases: ["mrk"] },
    { name: "Luke", aliases: ["luk"] },
    { name: "John", aliases: ["jhn"] },
    { name: "Acts", aliases: ["act"] },
    { name: "Romans", aliases: ["rom"] },
    { name: "1 Corinthians", aliases: ["1co", "1corinthians"] },
    { name: "2 Corinthians", aliases: ["2co", "2corinthians"] },
    { name: "Galatians", aliases: ["gal"] },
    { name: "Ephesians", aliases: ["eph"] },
    { name: "Philippians", aliases: ["php"] },
    { name: "Colossians", aliases: ["col"] },
    { name: "1 Thessalonians", aliases: ["1th", "1thessalonians"] },
    { name: "2 Thessalonians", aliases: ["2th", "2thessalonians"] },
    { name: "1 Timothy", aliases: ["1ti", "1timothy"] },
    { name: "2 Timothy", aliases: ["2ti", "2timothy"] },
    { name: "Titus", aliases: ["tit"] },
    { name: "Philemon", aliases: ["phm"] },
    { name: "Hebrews", aliases: ["heb"] },
    { name: "James", aliases: ["jas"] },
    { name: "1 Peter", aliases: ["1pe", "1peter"] },
    { name: "2 Peter", aliases: ["2pe", "2peter"] },
    { name: "1 John", aliases: ["1jn", "1john"] },
    { name: "2 John", aliases: ["2jn", "2john"] },
    { name: "3 John", aliases: ["3jn", "3john"] },
    { name: "Jude", aliases: ["jud"] },
    { name: "Revelation", aliases: ["rev"] },
];